export const scales = {
  ATR: {
    url: "ATR",
    granice: {
      female: {
        11: {
          ATR_U1: [10.5, 13, 16],
          ATR_U2: [17, 19, 20],
          ATR_U3: [4, 5, 7],
          ATR_U4: [7, 11, 13.5],
          ATR_N1: [4, 6, 8],
          ATR_N2: [11, 15, 18],
          ATR_N3: [4, 8, 11],
          ATR_N4: [5, 10, 12],
        },
        12: {
          ATR_U1: [11.75, 14, 16],
          ATR_U2: [16, 19, 20],
          ATR_U3: [4, 5, 8],
          ATR_U4: [8, 12, 14],
          ATR_N1: [4, 5.5, 10],
          ATR_N2: [14, 16, 19],
          ATR_N3: [5, 9.5, 14],
          ATR_N4: [7.75, 10, 14],
        },
        13: {
          ATR_U1: [11, 14, 17],
          ATR_U2: [17, 18, 20],
          ATR_U3: [4, 5, 7],
          ATR_U4: [8, 12, 14],
          ATR_N1: [4, 4, 7],
          ATR_N2: [13.75, 16, 18.25],
          ATR_N3: [5, 9.5, 13],
          ATR_N4: [8, 11, 14],
        },
        14: {
          ATR_U1: [12, 14, 15.75],
          ATR_U2: [16, 18, 19],
          ATR_U3: [5, 6, 8],
          ATR_U4: [9, 12, 15],
          ATR_N1: [4, 5, 7],
          ATR_N2: [14, 16, 18],
          ATR_N3: [7.25, 11.5, 14],
          ATR_N4: [9, 12, 14],
        },
      },
      male: {
        11: {
          ATR_U1: [11.5, 14, 17],
          ATR_U2: [16, 18, 19.75],
          ATR_U3: [4, 5, 7],
          ATR_U4: [7.5, 10, 12],
          ATR_N1: [4, 7, 12],
          ATR_N2: [12, 16, 20],
          ATR_N3: [4, 9, 13],
          ATR_N4: [8, 11, 13],
        },
        12: {
          ATR_U1: [11, 14, 16],
          ATR_U2: [15, 18, 20],
          ATR_U3: [4, 6, 10.25],
          ATR_U4: [9, 11, 14],
          ATR_N1: [4, 9, 13],
          ATR_N2: [12, 16, 19],
          ATR_N3: [8, 12, 16],
          ATR_N4: [9.25, 13, 16],
        },
        13: {
          ATR_U1: [13.75, 15.5, 17],
          ATR_U2: [16, 18, 20],
          ATR_U3: [4, 5, 8],
          ATR_U4: [8, 10, 15],
          ATR_N1: [4, 6, 10],
          ATR_N2: [13, 16, 19],
          ATR_N3: [7.75, 10.5, 14],
          ATR_N4: [9, 12, 15],
        },
        14: {
          ATR_U1: [13, 15, 17.75],
          ATR_U2: [15, 18, 20],
          ATR_U3: [4, 5, 7],
          ATR_U4: [9, 12, 15],
          ATR_N1: [4, 4, 11.5],
          ATR_N2: [12, 15, 19],
          ATR_N3: [8, 12, 15],
          ATR_N4: [10, 12, 16],
        },
      },
    },
    sumsImena: {
      ATR_U1: "Atribucija uspjeha unutrašnjim stabilnim uzrocima: Sposobnost",
      ATR_U2: "Atribucija uspjeha unutrašnjim nestabilnim uzrocima: Trud",
      ATR_U3: "Atribucija uspjeha vanjskim stabilnim uzrocima: Učitelj",
      ATR_U4: "Atribucija uspjeha vanjskim nestabilnim uzrocima: Sreća",
      ATR_N1:
        "Atribucija neuspjeha unutrašnjim stabilnim uzrocima: Nedostatak sposobnosti",
      ATR_N2:
        "Atribucija neuspjeha unutrašnjim nestabilnim uzrocima: Nedostatak truda",
      ATR_N3: "Atribucija neuspjeha vanjskim stabilnim uzrocima: Škola",
      ATR_N4: "Atribucija neuspjeha vanjskim nestabilnim uzrocima: Slučajnost",
    },
    skale: [
      "ATR_U1",
      "ATR_U2",
      "ATR_U3",
      "ATR_U4",
      "ATR_N1",
      "ATR_N2",
      "ATR_N3",
      "ATR_N4",
    ],
    n_skala: {
      ATR_U1: 4,
      ATR_U2: 4,
      ATR_U3: 4,
      ATR_U4: 4,
      ATR_N1: 4,
      ATR_N2: 4,
      ATR_N3: 4,
      ATR_N4: 4,
    },
    skalaIme: "Skala atribucija školskog uspjeha i neuspjeha",
    pitanja: [
      "Dobio sam lošu ocjenu jer učitelji ne znaju učiniti zadatke zanimljivima.",
      "Dobio sam lošu ocjenu jer su školski zadaci besmisleni i beskorisni.",
      "Dobio sam lošu ocjenu jer su predmeti i učenje dosadni.",
      "Dobio sam lošu ocjenu jer ono što me pitaju neće mi nikada trebati u životu.",
      "Dobio sam lošu ocjenu jer se nisam dovoljno pripremao za ispit.",
      "Dobio sam lošu ocjenu jer to gradivo nisam dobro naučio.",
      "Dobio sam lošu ocjenu jer nisam pazio što radim na ispitu.",
      "Dobio sam lošu ocjenu jer nisam redovito vježbao i pisao zadaće.",
      "Dobio sam lošu ocjenu jer sam loš učenik.",
      "Dobio sam lošu ocjenu jer sam nesposoban.",
      "Dobio sam lošu ocjenu jer nisam u stanju naučiti za dobru ocjenu.",
      "Dobio sam lošu ocjenu jer nisam dovoljno pametan.",
      "Dobio sam lošu ocjenu jer je u testu bilo nešto što još nismo učili.",
      "Dobio sam lošu ocjenu jer smo pisali test kasno, zadnje sate nastave.",
      "Dobio sam lošu ocjenu jer je moja grupa dobila test s težim pitanjima.",
      "Dobio sam lošu ocjenu jer ispit nije bio najavljen.",
      "Dobio sam dobru ocjenu jer sam sposoban.",
      "Dobio sam dobru ocjenu jer sam bistar učenik.",
      "Dobio sam dobru ocjenu jer sam pametan.",
      "Dobio sam dobru ocjenu jer bez truda mogu riješiti sve zadatke.",
      "Dobio sam dobru ocjenu jer sam učiteljev omiljeni učenik.",
      "Dobio sam dobru ocjenu jer mi učitelji uvijek daju dobre ocjene, bez obzira na moj trud i znanje.",
      "Dobio sam dobru ocjenu jer me učitelj (učiteljica) voli.",
      "Dobio sam dobru ocjenu mi učitelj uvijek postavlja lagana pitanja.",
      "Dobio sam dobru ocjenu su me pitali baš ona pitanja koja sam znao.",
      "Dobio sam dobru ocjenu sam dobio grupu s lakšim pitanjima.",
      "Dobio sam dobru ocjenu sam na tom ispitu imao sreće.",
      "Dobio sam dobru ocjenu je tog dana učiteljica bila dobre volje.",
      "Dobio sam dobru ocjenu sam bio pažljiv u rješavanju zadataka.",
      "Dobio sam dobru ocjenu sam redovito pisao zadaće.",
      "Dobio sam dobru ocjenu sam se potrudio pripremiti za ispit.",
      "Dobio sam dobru ocjenu sam to gradivo dobro naučio.",
    ],
    sumsTemplate: {
      ATR_U1: [17, 18, 19, 20],
      ATR_U2: [29, 30, 31, 32],
      ATR_U3: [21, 22, 23, 24],
      ATR_U4: [25, 26, 27, 28],
      ATR_N1: [9, 10, 11, 12],
      ATR_N2: [5, 6, 7, 8],
      ATR_N3: [1, 2, 3, 4],
      ATR_N4: [13, 14, 15, 16],
    },
  },
  COR: {
    url: "COR",
    granice: {
      female: {
        11: {
          CI3: [5, 9, 11.5],
          CI4: [4.5, 9, 12.5],
          CU2: [15, 17, 19],
          CI1: [7, 10, 16],
          NA2: [6.5, 9, 13.5],
          NA1: [6, 8, 13.75],
          CI2: [5, 7, 9],
          CU1: [18, 19, 20],
        },
        12: {
          CI3: [6.75, 9, 11],
          CI4: [6, 9, 13],
          CU2: [13, 15.5, 18],
          CI1: [8.75, 13, 15],
          NA2: [5, 10, 14],
          NA1: [6.75, 10, 14],
          CI2: [3, 6.5, 9],
          CU1: [14, 17, 20],
        },
        13: {
          CI3: [6, 8, 10],
          CI4: [5, 9, 12],
          CU2: [11, 14, 16],
          CI1: [6, 12, 15],
          NA2: [8, 11, 15],
          NA1: [8, 11, 13],
          CI2: [3, 6, 9],
          CU1: [15, 17, 19],
        },
        14: {
          CI3: [5.25, 7.5, 9],
          CI4: [6, 9, 11],
          CU2: [10, 12, 15],
          CI1: [9.25, 10, 14.75],
          NA2: [8, 10.5, 14.75],
          NA1: [9, 11.5, 13.75],
          CI2: [4, 6, 7],
          CU1: [14, 16, 18],
        },
      },
      male: {
        11: {
          CI3: [7, 11, 14],
          CI4: [7.25, 12, 15],
          CU2: [14, 17, 19],
          CI1: [12, 15, 18],
          NA2: [9, 13, 15],
          NA1: [8, 13, 16],
          CI2: [5, 8, 10],
          CU1: [16, 18, 20],
        },
        12: {
          CI3: [6.75, 10, 12.25],
          CI4: [8.5, 13, 16],
          CU2: [12, 17, 19],
          CI1: [10, 14.5, 18],
          NA2: [6.75, 12, 16.25],
          NA1: [8.75, 12, 14.25],
          CI2: [6.25, 8.5, 11],
          CU1: [15, 18, 20],
        },
        13: {
          CI3: [7, 10, 12],
          CI4: [8, 11, 14],
          CU2: [11, 14, 17],
          CI1: [11, 13, 16],
          NA2: [10, 12, 16],
          NA1: [9, 12.5, 16],
          CI2: [5, 8, 9],
          CU1: [14, 17, 19],
        },
        14: {
          CI3: [6, 9, 10],
          CI4: [8, 10.5, 14],
          CU2: [11.25, 13, 16.75],
          CI1: [10, 14, 17],
          NA2: [11, 13, 16],
          NA1: [9.75, 13, 17],
          CI2: [5, 7, 10],
          CU1: [14, 16, 18],
        },
      },
    },
    sumsImena: {
      CU1: "Cilj približavanja učenju",
      CU2: "Cilj izbjegavanja pogrešaka",
      CI1: "Cilj približavanja kompeticiji",
      CI2: "Cilj izbjegavanja kompeticije",
      CI3: "Cilj samozaštite",
      CI4: "Cilj samopromocije",
      NA1: "Cilj izbjegavanja rada",
      NA2: "Socijalni cilj",
    },
    skale: ["CU1", "CU2", "CI1", "CI2", "CI3", "CI4", "NA1", "NA2"],
    n_skala: {
      CU1: 4,
      CU2: 4,
      CI1: 4,
      CI2: 3,
      CI3: 3,
      CI4: 4,
      NA1: 4,
      NA2: 4,
    },
    skalaIme: "Skala ciljanih orjentacija u učenju",
    pitanja: [
      "Pazim da ne bih ispao glup pred drugima u razredu.",
      "Trudim se uglavnom zato što se ne želim osramotiti pred drugima.",
      "Ne želim da drugi misle da nisam dovoljno pametan.",
      "Želim pokazati drugima da sam među najpametnijim učenicima u razredu.",
      "Želim pokazati drugima da sam pametan i da se ne trebam truditi oko učenja.",
      "Važno mi je da drugi misle da sam pametan i bistar.",
      "Važno mi je pokazati drugima da sam dovoljno pametan da mogu riješiti sve zadatke lako i bez problema.",
      "Želim biti temeljit i pažljiv u učenju kako ne bih propustio naučiti čak i ono što neće biti na ispitu.",
      "Želim riješiti zadatke svake domaće zadaće bez greške, čak i ako znam da zadaća neće biti pregledana.",
      "Želim izbjeći sve moguće greške, čak i na zadacima koji se ne ocjenjuju.",
      "Iako znam da me profesor neće baš sve pitati, moram naučiti sve iz gradiva koje učim.",
      "Jako sam zadovoljan kada sam u školi bolji od drugih.",
      "Posebno mi je drago kada na testu dobijem više bodova od drugih u razredu.",
      "Želim imati bolje ocjene od drugih učenika u razredu.",
      "Važno mi je biti uspješniji od drugih učenika u razredu.",
      "Volim nasmijavati prijatelje u razredu.",
      "Najzadovoljniji sam kada nasmijem cijeli razred duhovitim komentarima na nastavi i odmoru.",
      "U razredu se volim zafrkavati i dobacivati za vrijeme nastave.",
      "Volim zafrkavati učenike koji imaju dobre ocjene.",
      "Želim što manje vremena potrošiti na školske obaveze.",
      "Ne želim se truditi oko školskih obaveza više nego što je potrebno.",
      "U školi ne želim raditi više od onoga što moram.",
      "Pokušavam udovoljiti školskim obavezama sa što je moguće manje truda.",
      "Ne želim se dovesti u situaciju da netko drugi ima bolji uspjeh od mene.",
      "Ne mogu dopustiti da me drugi učenici preteknu u uspjehu na važnim testovima.",
      "Nije mi svejedno ako ne uspijem biti najbolji na testu.",
      "U školi mi je najvažnije naučiti zanimljive stvari s razumijevanjem.",
      "U školi uvijek želim naučiti nešto novo i interesantno",
      "Važno mi je napredovati u nekim znanjima i vještinama",
      "Važno mi je usvojiti i naučiti što više novih znanja i vještina",
    ],
    sumsTemplate: {
      CU1: [27, 28, 29, 30],
      CU2: [8, 9, 10, 11],
      CI1: [12, 13, 14, 15],
      CI2: [24, 25, 26],
      CI3: [1, 2, 3],
      CI4: [4, 5, 6, 7],
      NA1: [20, 21, 22, 23],
      NA2: [16, 17, 18, 19],
    },
  },
  SSU: {
    url: "SSU",
    granice: {
      female: {
        11: {
          MKK2: [28, 31, 34],
          PKP1: [5, 7, 11.5],
          PKP2: [4.5, 10, 13],
          MKK1: [14, 16, 18.5],
          DKP2: [22.5, 27, 31],
          DKP3: [12, 14, 17],
          DKP4: [14, 18, 21.5],
          DKP1: [13, 16, 18],
        },
        12: {
          MKK2: [24, 28, 33],
          PKP1: [5, 8.5, 13],
          PKP2: [5.5, 10, 13],
          MKK1: [13.75, 16, 19],
          DKP2: [21.75, 26, 31],
          DKP3: [12, 14, 16],
          DKP4: [14, 17, 20],
          DKP1: [12, 14, 16],
        },
        13: {
          MKK2: [26, 29, 33],
          PKP1: [5, 7, 10],
          PKP2: [6, 8, 11],
          MKK1: [12, 15, 17],
          DKP2: [24, 31, 33],
          DKP3: [12, 15, 16.25],
          DKP4: [14, 17, 20],
          DKP1: [13, 16, 19],
        },
        14: {
          MKK2: [26, 29, 33],
          PKP1: [4, 6, 10.75],
          PKP2: [5, 9, 12.75],
          MKK1: [13, 15, 17],
          DKP2: [24, 27, 30],
          DKP3: [12, 14, 16],
          DKP4: [14.25, 16.5, 20],
          DKP1: [12, 14, 16],
        },
      },
      male: {
        11: {
          MKK2: [23, 27, 32],
          PKP1: [8, 11, 15],
          PKP2: [8.75, 12.5, 16],
          MKK1: [12, 14.5, 19],
          DKP2: [21.75, 25, 29.25],
          DKP3: [12, 14, 18],
          DKP4: [15, 18, 22],
          DKP1: [12, 15, 18],
        },
        12: {
          MKK2: [21.25, 26.5, 33.5],
          PKP1: [4, 10.5, 14.25],
          PKP2: [10, 13, 16],
          MKK1: [12.25, 15.5, 20],
          DKP2: [20, 24, 31],
          DKP3: [13, 15, 18],
          DKP4: [15, 18, 21.25],
          DKP1: [12, 15, 18],
        },
        13: {
          MKK2: [24, 27, 31],
          PKP1: [5, 8, 13],
          PKP2: [9, 11, 14],
          MKK1: [12, 14, 17],
          DKP2: [21, 25, 29.25],
          DKP3: [12, 14, 16],
          DKP4: [14.75, 17, 19],
          DKP1: [12, 14, 17.25],
        },
        14: {
          MKK2: [21.25, 25, 28.75],
          PKP1: [5, 9.5, 13],
          PKP2: [7, 9.5, 12.75],
          MKK1: [12, 14, 17],
          DKP2: [19, 24, 27],
          DKP3: [12, 13, 16],
          DKP4: [14.25, 16.5, 19],
          DKP1: [12, 15, 16.75],
        },
      },
    },
    sumsImena: {
      MKK1: "Ponavljanje i uvježbavanje",
      MKK2: "Kontrola tijeka i ishoda učenja",
      DKP1: "Elaboracija",
      DKP2: "Organizacija",
      DKP3: "Primjena",
      DKP4: "Kritičko mišljenje",
      PKP1: "Usmjerenost na minimalne zahtjeve",
      PKP2: "Memoriranje",
    },
    skale: ["MKK1", "MKK2", "DKP1", "DKP2", "DKP3", "DKP4", "PKP1", "PKP2"],
    n_skala: {
      MKK1: 4,
      MKK2: 7,
      DKP1: 4,
      DKP2: 7,
      DKP3: 4,
      DKP4: 6,
      PKP1: 4,
      PKP2: 4,
    },
    skalaIme: "Skala strategija učenja",
    pitanja: [
      "Nakon učenja provjerim svoje znanje i razumijevanje gradiva.",
      "Kada učim, pokušavam utvrditi postoji li nešto što nisam dobro razumio.",
      "Za vrijeme učenja često sam sebi postavljam pitanja da bih bio siguran jesam li sve dobro razumio.",
      "Dok učim, sve što mi je nejasno pročitam ponovo kako bih to što bolje razumio.",
      "Prije ispita provjerim svoje znanje i spremnost za ispit.",
      "Dok učim, stalno pokušavam provjeriti je li mi sve jasno.",
      "Kada učim, često se vraćam na dijelove koje nisam razumio ili mi izgledaju nejasni.",
      "Koncentriram se samo na učenje onih sadržaja koji su dovoljni za prolaz.",
      "Učim samo onoliko koliko je potrebno za prolaznu ocjenu.",
      "Provjerim koliko toga treba naučiti da bih dobio prolaznu ocjenu.",
      "Nikada ne učim više od onoga što je zadano.",
      "Gradivo uglavnom učim doslovno i napamet.",
      "Često učim napamet i pokušavam sve zapamtiti upravo onako kako je napisano u knjizi ili bilježnici jer su takva pitanja na ispitu.",
      "Prije ispita učim napamet sve detalje kako bih mogao na sva pitanja točno odgovoriti.",
      "Kad učim za ispit, ne gubim vrijeme na razmišljanje o onome što učim, nego pokušavam sve doslovno zapamtiti.",
      "Da bih se spremio za ispit, pročitam bilježnicu ili knjigu više puta ili riješim puno zadataka.",
      "Ponavljam gradivo dok ga ne naučim i uvježbavam izvođenje zadatka više puta dok ne budem brz i točan.",
      "Kada učim, najčešće se pripremam tako da više puta pročitam gradivo ili uvježbam mnoge zadatke koje moram riješiti.",
      "Kada želim nešto naučiti, najčešće ponavljam gradivo ili uvježbavam zadatke nekoliko puta.",
      "Opsežne tekstove pokušavam sažeti i osmisliti u par važnih rečenica ili natuknica.",
      "Velika gradiva pokušavam podijeliti u više malih cjelina koje su razumljive i smislene.",
      "Dok čitam tekst, podcrtavam važne dijelove ili radim zabilješke na rubovima stranica kako bih naglasio važne izraze.",
      "Pokušavam istaknuti važne dijelove teksta kako bih gradivo lakše naučio i razumio.",
      "Učeći pokušavam razlikovati važne od nevažnih informacija.",
      "Na velikim i nejasnim tekstovima izdvojim na papir nekoliko važnih termina i ideja kako bih gradivo bolje razumio.",
      "Pokušavam osmisliti kako se sadržaji koje učim mogu podijeliti u smislene grupe.",
      "Ono što učim ponekad mi postane jasno tek kada to nacrtam, napravim ili primijenim.",
      "Mnoge stvari lakše naučim ako ih nekako zamislim ili predočim.",
      "Pravo znanje i vještinu postignem tek kada na konkretnim problemima provedem i primijenim ono što sam naučio.",
      "Nastojim ono što sam naučio upotrijebiti u drugim aktivnostima, na drugim satovima i izvan nastave.",
      "Dok učim, ponekad dobijem vlastitu ideju kako bi nešto moglo biti bolje napravljeno.",
      "Kada nastavnica nešto objasni i ponudi rješenje, zapitam se može li se to riješiti i na drugačiji način.",
      "Odmah primijetim ako se ista stvar opisuje i objašnjava na različite načine i pokušavam utvrditi što je ispravno.",
      "Dok učim, uvijek imam na umu da svako objašnjenje ima prednosti i nedostatke.",
      "Kad god pročitam ili čujem neku tvrdnju ili zaključak razmišljam je li točna i može li se poboljšati.",
      "Kada god je to moguće, pokušavam povezati gradivo koje učim s onim što sam naučio na drugim predmetima ili što sam saznao od drugih.",
      "Pokušavam povezati informacije koje učim s gradivom iz različitih predmeta i informacijama koje sam dobio izvan škole.",
      "Pokušavam razumjeti novo gradivo povezujući ga s onim što već znam i što mi je jasno.",
      "Dok čitam gradivo nekog predmeta, pokušavam ga povezati s onim što već znam.",
    ],
    sumsTemplate: {
      MKK1: [10, 11, 12, 13],
      MKK2: [14, 15, 16, 17],
      DKP1: [18, 19, 20, 21],
      DKP2: [23, 24, 25, 26],
      DKP3: [1, 2, 3, 4, 5],
      DKP4: [27, 28, 29, 30, 31, 32, 33, 34],
      PKP1: [35, 36, 37, 38],
      PKP2: [6, 7, 8, 9],
    },
  },
  SUN: {
    url: "SUN",
    granice: {
      male: {
        11: {
          S_EMU3: [8, 14, 16],
          S_EGU3: [5.75, 12, 14],
          S_P1: [15, 17, 19],
          S_EMU1: [7, 14, 18],
          S_EMU2: [11, 13, 16],
          S_EGU1: [14, 23, 28],
          S_EGU2: [10, 12, 15],
          S_P2: [13, 16, 19],
        },
        12: {
          S_EMU3: [5, 15, 20],
          S_EGU3: [7.5, 12, 16],
          S_P1: [15, 18, 20],
          S_EMU1: [8, 14, 19],
          S_EMU2: [9.5, 13, 16.5],
          S_EGU1: [13, 23, 27],
          S_EGU2: [8.5, 12, 15],
          S_P2: [13, 18, 19],
        },
        13: {
          S_EMU3: [10, 15, 18.25],
          S_EGU3: [6, 10.5, 13],
          S_P1: [15, 16.5, 19.25],
          S_EMU1: [6.75, 11, 15.25],
          S_EMU2: [10, 12, 15],
          S_EGU1: [14.75, 20, 27],
          S_EGU2: [9, 12, 14.25],
          S_P2: [13, 15.5, 19],
        },
        14: {
          S_EMU3: [9, 13, 16],
          S_EGU3: [7, 12, 14],
          S_P1: [14, 16, 19],
          S_EMU1: [5, 9.5, 14],
          S_EMU2: [8.75, 12, 16],
          S_EGU1: [12, 20.5, 25],
          S_EGU2: [9, 12, 13],
          S_P2: [12.75, 15, 17],
        },
      },
      female: {
        11: {
          S_EMU3: [5, 13, 17],
          S_EGU3: [4.5, 11.5, 16],
          S_P1: [17, 19, 20],
          S_EMU1: [5.25, 11, 14],
          S_EMU2: [9, 12, 16],
          S_EGU1: [13, 20, 25],
          S_EGU2: [8, 10, 14],
          S_P2: [14, 18, 19],
        },
        12: {
          S_EMU3: [7, 13, 17],
          S_EGU3: [5, 9, 13],
          S_P1: [16, 19, 20],
          S_EMU1: [6, 12, 16],
          S_EMU2: [10, 13, 16],
          S_EGU1: [14, 21, 25],
          S_EGU2: [8, 11, 15],
          S_P2: [14, 18, 19],
        },
        13: {
          S_EMU3: [9, 14, 18],
          S_EGU3: [8, 12, 15],
          S_P1: [16, 19, 20],
          S_EMU1: [6, 11, 17],
          S_EMU2: [8, 12, 16],
          S_EGU1: [15.5, 20, 26],
          S_EGU2: [9, 12, 16],
          S_P2: [14, 16, 19],
        },
        14: {
          S_EMU3: [6, 9.5, 15],
          S_EGU3: [6, 9, 14],
          S_P1: [15, 17, 19],
          S_EMU1: [5, 6.5, 9.25],
          S_EMU2: [8, 10, 13],
          S_EGU1: [12, 17, 24],
          S_EGU2: [6, 10, 13],
          S_P2: [14, 17, 19],
        },
      },
    },
    sumsImena: {
      S_P1: "Aktivno rješavanje problema",
      S_P2: "Razmišljanje o problemu",
      S_EMU1: "Izbjegavanje",
      S_EMU2: "Maštanje",
      S_EMU3: "Skretanje pažnje",
      S_EGU1: "Odustajanje i reinterpretacija",
      S_EGU2: "Ignoriranje problema",
      S_EGU3: "Ismijavanje problema",
    },
    skale: [
      "S_P1",
      "S_P2",
      "S_EMU1",
      "S_EMU2",
      "S_EMU3",
      "S_EGU1",
      "S_EGU2",
      "S_EGU3",
    ],
    n_skala: {
      S_P1: 4,
      S_P2: 4,
      S_EMU1: 5,
      S_EMU2: 4,
      S_EMU3: 5,
      S_EGU1: 8,
      S_EGU2: 4,
      S_EGU3: 4,
    },
    skalaIme: "Skala suočavanja sa školskim neuspjehom",
    pitanja: [
      "Češće se bavim sportom, trčim ili se igram na ulici da ne bih razmišljao o lošoj ocjeni.",
      "Bavim se drugim stvarima da bih što prije zaboravio lošu ocjenu.",
      "Idem u šetnju ili izađem van da više ne bih bio napet zbog loše ocjene.",
      "Više treniram, vježbam i rekreiram se da ne bih mislio na lošu ocjenu.",
      "Čitam romane ili crtam nešto da bih lošu ocjenu smetnuo s uma.",
      "Nastojim pronaći šaljivu stranu takve situacije.",
      "Šalim se na račun loše ocjene.",
      "Ismijavam taj problem da ne izgleda jako težak.",
      "Smijem se na račun tog problema da bih se osjećao bolje.",
      "Učim više da bih dobio bolju ocjenu.",
      "Provodim više vremena učeći predmet iz kojeg sam dobio lošu ocjenu.",
      "Potrudim se više ne dobivati loše ocjene.",
      "Odlučim da ću se javiti da bih ispravio ocjenu.",
      "Koncentriram se na prvu stvar koju ću učiniti da bih ispravio ocjenu.",
      "Razmišljam što je najbolje napraviti da bih popravio ocjenu.",
      "Smišljam načine kako ispraviti ocjenu.",
      "Napravim plan učenja i ponavljanja da bih što prije ispravio ocjenu.",
      "Izbjegavam sve što me podsjeća na lošu ocjenu.",
      "Odlazim spavati da ne bih morao razmišljati o lošoj ocjeni.",
      "Udaljim se od ljudi i mjesta koja me podsjećaju na lošu ocjenu.",
      "Jednostavno legnem u krevet i pokušavam zaspati da ne bih bio opterećen lošom ocjenom.",
      "Izbjegavam situacije u kojima moram razmišljati ili govoriti o lošoj ocjeni.",
      "Poželim da ta loša ocjena jednostavno nestane.",
      "Poželim da se ta loša ocjena nikada nije dogodila.",
      "Maštam o tome da se dogodi neko čudo i izbriše lošu ocjenu.",
      "Maštam da se ta loša ocjena nije dogodila.",
      "Pomirim se s lošom ocjenom.",
      "Pomirim se s lošom ocjenom jer ništa drugo ne mogu učiniti.",
      "Prihvaćam da se to dogodilo i da se ne može promijeniti.",
      "Kažem sam sebi kako nije tako strašno dobiti lošu ocjenu.",
      "Mislim kako uopće nije važno to što sam dobio lošu ocjenu.",
      "Razmišljam da je dobro što sam dobio lošu ocjenu jer ću za drugi put znati bolje.",
      "Mislim da nikada neću uspjeti u tom predmetu.",
      "Odustajem od pokušaja da popravim lošu ocjenu.",
      "Pravim se kao da me se loša ocjena ne tiče.",
      "Ne razmišljam o lošoj ocjeni.",
      "Pokušavam ne misliti o lošoj ocjeni da mi ne bi bilo još teže.",
      "Radim sve kao da uopće nisam dobio lošu ocjenu.",
    ],
    sumsTemplate: {
      S_P1: [10, 11, 12, 13],
      S_P2: [14, 15, 16, 17],
      S_EMU1: [18, 19, 20, 21, 22],
      S_EMU2: [23, 24, 25, 26],
      S_EMU3: [1, 2, 3, 4, 5],
      S_EGU1: [27, 28, 29, 30, 31, 32, 33, 34],
      S_EGU2: [35, 36, 37, 38],
      S_EGU3: [6, 7, 8, 9],
    },
  },
  TSP: {
    url: "TSP",
    granice: {
      male: {
        11: {
          TSP_P: [9, 15, 20],
          TSP_R: [16, 21, 24],
          TSP_NE: [3, 6, 10],
          TSP_NI: [7, 10, 13],
        },
        12: {
          TSP_P: [13.5, 18, 23],
          TSP_R: [18, 22, 26.5],
          TSP_NE: [5, 8, 10],
          TSP_NI: [9, 10, 14],
        },
        13: {
          TSP_P: [12, 17, 21.25],
          TSP_R: [13.75, 19, 22.25],
          TSP_NE: [3.75, 6, 9.25],
          TSP_NI: [9, 11, 12.25],
        },
        14: {
          TSP_P: [9, 14.5, 18.25],
          TSP_R: [11.75, 16, 20],
          TSP_NE: [3, 6, 9],
          TSP_NI: [6, 9, 11.25],
        },
      },
      female: {
        11: {
          TSP_P: [11.5, 18.5, 23],
          TSP_R: [15.25, 19, 24.75],
          TSP_NE: [3.25, 6, 9.75],
          TSP_NI: [9, 11, 13],
        },
        12: {
          TSP_P: [14, 20, 24],
          TSP_R: [18, 21, 25],
          TSP_NE: [3, 6, 8.25],
          TSP_NI: [8, 11, 14],
        },
        13: {
          TSP_P: [14.5, 18, 24],
          TSP_R: [11.5, 18, 22.5],
          TSP_NE: [3, 5, 7.5],
          TSP_NI: [8, 10, 14],
        },
        14: {
          TSP_P: [13, 17, 22.25],
          TSP_R: [12, 15, 19.5],
          TSP_NE: [3, 4, 9],
          TSP_NI: [8, 9.5, 13],
        },
      },
    },
    sumsImena: {
      TSP_P: "Traženje emocionalne i instrumentalne podrške od prijatelja",
      TSP_R: "Traženje emocionalne i instrumentalne podrške od roditelja",
      TSP_NE: "Traženje emocionalne podrške od nastavnika",
      TSP_NI: "Traženje instrumentalne podrške od nastavnika",
    },
    skale: ["TSP_P", "TSP_R", "TSP_NE", "TSP_NI"],
    n_skala: {
      TSP_P: 6,
      TSP_R: 6,
      TSP_NE: 3,
      TSP_NI: 3,
    },
    skalaIme: "Skala traženja socijalne podrške",
    pitanja: [
      "Tražim utjehu od prijatelja.",
      "Razgovaram s prijateljima da bih se osjećao bolje.",
      "Pokušavam dobiti simpatije i razumijevanje svojih prijatelja.",
      "Kada dobijem lošu ocjenu, tražim pomoć od prijatelja.",
      "Tražim savjet od prijatelja kada želim popraviti lošu ocjenu.",
      "Razgovaram s prijateljima koji mi mogu pomoći kada dobijem lošu ocjenu.",
      "Razgovaram s roditeljima kako se više ne bih loše osjećao.",
      "Očekujem da me roditelji utješe.",
      "Pokušavam dobiti simpatije i razumijevanje od roditelja.",
      "Razgovaram s roditeljima da bi mi pomogli ispraviti ocjenu.",
      "Savjetujem se s mamom ili tatom što učiniti kada dobijem lošu ocjenu.",
      "Tražim od roditelja da mi pomognu naučiti za bolju ocjenu.",
      "Razgovaram s nastavnikom da bih se umirio.",
      "Razgovaram s nastavnikom da bih se osjećao bolje.",
      "Požalim se nastavniku.",
      "Pitam nastavnika da mi objasni gdje sam napravio greške.",
      "Zamolim nastavnika da mi pomogne i objasni gradivo.",
      "Zamolim nastavnika da mi pokaže kako mogu popraviti ocjenu.",
    ],
    sumsTemplate: {
      TSP_P: [1, 2, 3, 4, 5, 6],
      TSP_R: [7, 8, 9, 10, 11, 12],
      TSP_NE: [13, 14, 15],
      TSP_NI: [16, 17, 18],
    },
  },
  UKO: {
    url: "UKO",
    granice: {
      female: {
        11: {
          UKO_P1: [17, 19, 20],
          UKO_P2: [14.25, 16.5, 19.25],
          UKO_O1: [4, 6, 9.75],
          UKO_O2: [4, 9, 12],
          UKO_O3: [6, 8, 12.5],
        },
        12: {
          UKO_P1: [14, 17, 20],
          UKO_P2: [14, 18, 20],
          UKO_O1: [4, 8, 12],
          UKO_O2: [5, 9, 12],
          UKO_O3: [6, 10, 12.25],
        },
        13: {
          UKO_P1: [15, 17, 19.5],
          UKO_P2: [15, 19, 20],
          UKO_O1: [4, 8, 11],
          UKO_O2: [4.5, 8, 11],
          UKO_O3: [7, 10, 13],
        },
        14: {
          UKO_P1: [16, 19, 20],
          UKO_P2: [16, 19, 20],
          UKO_O1: [4, 7, 10],
          UKO_O2: [4.75, 7.5, 9.25],
          UKO_O3: [8, 10.5, 13],
        },
      },
      male: {
        11: {
          UKO_P1: [15, 17, 20],
          UKO_P2: [13, 14, 18],
          UKO_O1: [5, 8, 14],
          UKO_O2: [10, 12, 14.5],
          UKO_O3: [8, 10, 13],
        },
        12: {
          UKO_P1: [14, 17, 20],
          UKO_P2: [13, 17, 20],
          UKO_O1: [8.5, 12, 14],
          UKO_O2: [10, 12.5, 15],
          UKO_O3: [8.5, 12, 13.5],
        },
        13: {
          UKO_P1: [15.75, 17.5, 20],
          UKO_P2: [14, 16.5, 20],
          UKO_O1: [7, 9, 14],
          UKO_O2: [7.5, 12, 14],
          UKO_O3: [6, 10, 12],
        },
        14: {
          UKO_P1: [14, 16, 19],
          UKO_P2: [12, 16, 20],
          UKO_O1: [7, 10, 13.25],
          UKO_O2: [7.75, 9.5, 13],
          UKO_O3: [8, 10, 14],
        },
      },
    },
    sumsImena: {
      UKO_P1: "Uvjerenje da je za ostvarenje ciljeva potreban trud",
      UKO_P2: "Opće uvjerenje o mogućnosti kontrole",
      UKO_O1: "Uvjerenje da ostvarenje ciljeva ovisi o vanjskim čimbenicima",
      UKO_O2: "Uvjerenje da je za ostvarenje ciljeva potrebna sposobnost",
      UKO_O3: "Uvjerevanje o nepromjenjivosti kognitivnih sposobnosti",
    },
    skale: ["UKO_P1", "UKO_P2", "UKO_O1", "UKO_O2", "UKO_O3"],
    n_skala: {
      UKO_P1: 4,
      UKO_P2: 4,
      UKO_O1: 4,
      UKO_O2: 4,
      UKO_O3: 4,
    },
    skalaIme: "Skala kognitivnih uvjerenja o kontroli",
    pitanja: [
      "Da bi dobio dobru ocjenu, moraš imati sreće i nastavnika koji nije strog.",
      "Hoćeš li postići dobar rezultat na testu ovisi o tome imaš li sreće i dobrog nastavnika.",
      "Učenikovo postignuće u školi uglavnom ovisi o sreći ili nastavniku.",
      "Uspjeh u školi više ovisi o nastavniku i sreći nego o trudu.",
      "Mogu imati dobar uspjeh u školi ako se odlučim na to.",
      "Ako želim, lako mogu dobiti dobre ocjene.",
      "Nije mi problem biti dobar učenik kada se na to odlučim.",
      "Ako hoću, mogu naučiti sve što u školi traže.",
      "Neke svoje osobine jednostavno ne možeš promijeniti (ne možeš postati pametniji i bistriji nego što jesi).",
      "Neki ljudi su pametni, a neki jednostavno nisu pametni i to ne mogu promijeniti koliko god se trudili.",
      "Ako se trudiš možeš naučiti i zapamtiti mnoge stvari, ali to ti neće pomoći da postaneš pametniji.",
      "To koliko si pametan i bistar ne ovisi o trudu.",
      "Do dobrih ocjena dolazi se samo radom i vježbom.",
      "Sve se može naučiti uz dovoljno truda i rada.",
      "Loše ocjene se dobiju ako se ne trudiš dovoljno.",
      "Postići ćeš dobar uspjeh u školi samo ako se dovoljno trudiš.",
      "Učenik koji nije dovoljno pametan i sposoban ne može biti uspješan u školi.",
      "Loš uspjeh u školi posljedica je nesposobnosti.",
      "Moraš biti pametan da bi dobio dobre ocjene.",
      "Ukoliko neki učenik ne nauči gradivo, to je zbog toga što nije dovoljno pametan.",
    ],
    sumsTemplate: {
      UKO_P1: [13, 14, 15, 16],
      UKO_P2: [5, 6, 7, 8],
      UKO_O1: [1, 2, 3, 4],
      UKO_O2: [17, 18, 19, 20],
      UKO_O3: [9, 10, 11, 12],
    },
  },
  ANX: {
    url: "ANX",
    granice: {
      male: {
        11: {
          ANX1: [4, 6, 9],
          ANX2: [7, 9, 13],
          ANX3: [5, 7, 9],
        },
        12: {
          ANX1: [4.5, 7, 10],
          ANX2: [7.5, 11, 15],
          ANX3: [5, 7, 10],
        },
        13: {
          ANX1: [4, 7, 9],
          ANX2: [6.5, 10, 13],
          ANX3: [6, 7, 9],
        },
        14: {
          ANX1: [4, 6, 8],
          ANX2: [7, 9, 12],
          ANX3: [5, 7.5, 8],
        },
      },
      female: {
        11: {
          ANX1: [6, 7.5, 10],
          ANX2: [7, 9, 12],
          ANX3: [6.5, 8, 9],
        },
        12: {
          ANX1: [6, 9, 10],
          ANX2: [7, 10, 14],
          ANX3: [6, 8, 9],
        },
        13: {
          ANX1: [6, 8, 10],
          ANX2: [6, 11, 14],
          ANX3: [6, 8, 10],
        },
        14: {
          ANX1: [6, 7, 9.75],
          ANX2: [7, 9, 12],
          ANX3: [5, 7, 9],
        },
      },
      sumsImena: {
        ANX1: "Fiziološka komponenta anksioznosti",
        ANX2: "Emocionalna komponenta anksioznosti",
        ANX3: "Kognitivna i bihevioralna komponenta anksioznosti",
      },
      skale: ["ANX1", "ANX2", "ANX3"],
      n_skala: {
        ANX1: 2,
        ANX2: 2,
        ANX3: 4,
      },
    },
    skalaIme: "Skala ispitne anksioznosti",
    pitanja: [
      "Kad nastavnik ispituje, uvijek mi se pojavi neki čudan osjećaj u trbuhu.",
      "Još dok se dijele testovi ili bilježnice za školske zadaće, srce mi počne jako lupati.",
      "Ako na početku pismenog ispita ne uspijem riješiti prvi zadatak, jako se uzrujam i ne mogu se koncentrirati na druge zadatke.",
      "Za vrijeme pismenog ispitivanja u školi često zaboravim i ono što sam prije toga dobro naučio.",
      "Kada imamo pismeno ispitivanje u školi, najčešće već na početku znam da neću dobro proći na ispitu.",
      "Kad se piše školska zadaća ili test, često griješim jer se previše bojim.",
      "Uvijek sam napet prije nekog pismenog ispitivanja u školi.",
      "Katkad poželim da me ispitivanja u školi ne brinu tako jako.",
    ],
    sumsTemplate: {
      ANX1: [1, 2],
      ANX2: [7, 8],
      ANX3: [3, 4, 5, 6],
    },
  },
  ASE: {
    url: "ASE",
    granice: {
      male: {
        11: {
          ASE1: [12, 15, 17],
          ASE2: [13, 16, 19],
        },
        12: {
          ASE1: [12, 15.5, 17],
          ASE2: [12, 15, 17],
        },
        13: {
          ASE1: [9, 13, 15.5],
          ASE2: [11, 13.5, 16],
        },
        14: {
          ASE1: [11, 14, 15],
          ASE2: [11, 14, 17],
        },
      },
      female: {
        11: {
          ASE1: [14, 16, 18],
          ASE2: [14, 16, 18],
        },
        12: {
          ASE1: [12.75, 15.5, 18],
          ASE2: [12, 15, 17],
        },
        13: {
          ASE1: [12, 14, 17],
          ASE2: [12, 15, 19],
        },
        14: {
          ASE1: [12, 15, 16],
          ASE2: [13, 14.5, 17],
        },
      },
    },
    sumsImena: {
      ASE1: "Samoefikasnost u procesu učenja",
      ASE2: "Samoefikasnost u postizanju željenjih ishoda učenja",
    },
    skalaIme: "Skala akademske samoefikasnosti",
    pitanja: [
      "Uspješan sam u skoro svim školskim predmetima.",
      "Uspješno rješavam testove u školi.",
      "Mojim uspjehom u školi mogu zadovoljiti očekivanja roditelja.",
      "Kada me ispituju, pokazujem dobro znanje.",
      "Lako mi je pažljivo pratiti svaki školski sat.",
      "Lako mi je naučiti zadano gradivo za test.",
      "Lako se koncentriram na učenje, čak i kad sam okružen drugim zanimljivim stvarima.",
      "Lako i redovito rješavam domaće zadaće.",
    ],
    sumsTemplate: {
      ASE1: [5, 6, 7, 8],
      ASE2: [1, 2, 3, 4],
    },
  },
  MOST: {
    url: "MOST",
    granice: {
      male: {
        11: {
          MSS1: [6.5, 13, 17.5],
          MSU3: [20, 25, 28],
          MSS2: [9, 12, 15],
          MSU1: [13, 16, 17],
          MSU2: [13.75, 18.5, 21],
        },
        12: {
          MSS1: [9, 15, 17],
          MSU3: [20, 25, 28],
          MSS2: [10, 12, 14.25],
          MSU1: [13, 16, 19],
          MSU2: [15, 18, 22],
        },
        13: {
          MSS1: [9, 13, 17.25],
          MSU3: [20, 23, 27],
          MSS2: [8, 11, 13],
          MSU1: [13, 15, 16.25],
          MSU2: [13, 17, 19],
        },
        14: {
          MSS1: [10, 14, 16],
          MSU3: [19, 21, 26],
          MSS2: [9.25, 11, 13],
          MSU1: [12, 13.5, 16],
          MSU2: [14, 15, 18],
        },
      },
      female: {
        11: {
          MSS1: [5, 8, 11],
          MSU3: [22.5, 26, 28.5],
          MSS2: [9, 12, 14],
          MSU1: [13, 15, 17],
          MSU2: [17, 20, 21],
        },
        12: {
          MSS1: [6, 10, 16],
          MSU3: [21, 24, 29],
          MSS2: [8, 11, 14],
          MSU1: [12.75, 15, 18],
          MSU2: [16, 18, 21],
        },
        13: {
          MSS1: [8, 12, 17],
          MSU3: [20, 24, 28],
          MSS2: [9, 12, 13],
          MSU1: [14, 16, 18],
          MSU2: [14, 17, 21],
        },
        14: {
          MSS1: [7.25, 10, 15],
          MSU3: [20.5, 25, 29],
          MSS2: [8.75, 11, 12],
          MSU1: [12, 14, 16],
          MSU2: [14, 16, 19],
        },
      },
      sumsImena: {
        MSU1: "Postavljanje ciljeva",
        MSU2: "Reguliranje truda",
        MSU3: "Upravljanje radom, vremenom i okolinom",
        MSS1: "Samohendikepiranje",
        MSS2: "Obrambeni pesimizam",
      },
      n_skala: {
        MSU1: 4,
        MSU2: 5,
        MSU3: 6,
        MSS1: 5,
        MSS2: 4,
      },
    },
    pitanja: [
      "Kada naletim na težak dio gradiva ne odustanem nego se zainatim i učinim sve da bih ga savladao.",
      "Ako zapnem na teškom gradivu, sam se ohrabrujem i kažem si da ja to mogu riješiti.",
      "Dok rješavam neki težak zadatak, sam sebi kažem: 'Ja to mogu napraviti' i nastavim se truditi.",
      "Kada naletim na težak dio gradiva ne odustanem nego se zainatim i učinim sve da bih ga savladao.",
      "Kada sam već umoran od učenja, potrudim se još malo zamišljajući kako će biti lijepo kada završim zadatke",
      "Ako imam puno ispita, učim cijeli vikend i odgodim igranje, izlaske i zabavu.",
      "Uvijek očekujem lošu ocjenu tako da ne bih bio iznenađen ako ju dobijem.",
      "Često nakon ispita drugima kažem da ću sigurno dobiti lošu ocjenu i navedem neki razlog (npr. test je bio jako težak, neke zadatke nismo učili i sl.).",
      "Nikada se ne nadam dobroj ocjeni kako se ne bih razočarao.",
      "Roditeljima i prijateljima kažem da sam loše napisao test kako ne bi očekivali peticu.",
      "Uglavnom učim u prostoriji u kojoj se mogu koncentrirati na gradivo.",
      "Prije učenja pobrinem se da mogu raditi u miru.",
      "Volim koristiti uvijek isto mjesto za učenje.",
      "Volim sve bilježnice i knjige imati složene kraj svog mjesta za učenje da ih mogu brzo i lako naći.",
      "Planiram kada ću učiti, imajući na umu kada će biti ispiti.",
      "Pokušavam se što bolje organizirati da bih imao vremena za učenje i odmor.",
      "Sve učim tako da si sam postavim ciljeve i potrudim se izvršiti ono što sam si zadao.",
      "Prije nego krenem na učenje razmislim koliko dobro to trebam naučiti i ne odustajem dok nisam zadovoljan onim što sam postigao.",
      "Kada učim neko gradivo, odredim točno što želim postići učenjem.",
      "Sam odredim koliko toga trebam naučiti i trudim se dok to ne postignem.",
      "Učenje uvijek ostavim za zadnji trenutak.",
      "Kada treba najviše učiti, ja se počnem baviti drugim stvarima.",
      "Kada treba učiti za ispit, odjednom dobijem volju raditi nešto drugo, samo da ne učim.",
      "Dok svi uče pred ispite, ja se zabavljam.",
      "Svima dam do znanja da se uopće ne trudim oko učenja.",
    ],
    skalaIme: "Skala motivacijskih strategija",
    sumsTemplate: {
      MSU1: [16, 17, 18, 19],
      MSU2: [1, 2, 3, 4, 5],
      MSU3: [10, 11, 12, 13, 14, 15],
      MSS1: [20, 21, 22, 23, 24],
      MSS2: [6, 7, 8, 9],
    },
  },
};
